export const createStage = () => {}
export const pauseGame = () => {}
export const resumeGame = () => {}
export const moveLeft = () => {}
export const moveRight = () => {}
export const moveDown = () => {}
export const rotate = () => {}
export const drop = () => {}
export const restartGame = () => {}